server:
  port: 8100
spring:
  application:
    name: uaa
  cloud:
    inetutils:
      ignored-interfaces: eth.*
      preferred-networks: 182.92.5
    nacos:
      discovery:
        server-addr: 182.92.5.78:8848
        #ip: 182.92.5.78
    sentinel:
      transport:
        dashboard: 182.92.5.78:8180
        port: 8719
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:47.110.32.181}:${DATASOURCE_PORT:3306}/microservices-admin?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:1nncore.co.ltd}
#  redis:
#    host: 192.168.70.200
#    port: 6379
#    password: 123456

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.microservices.oauth.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-delete-field: deleted
      id-type: auto


feign:
  sentinel:
    enabled: true

logging:
  level:
    root: info
    com.example.microservices.oauth: info
