server:
  port: 8200
spring:
  application:
    name: user-admin
  cloud:
    nacos:
      discovery:
        server-addr: 134.175.47.234:8848
    sentinel:
      transport:
        dashboard: 134.175.47.234:8180
        port: 8719
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:134.175.47.234}:${DATASOURCE_PORT:3306}/rbac-security?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:Wangu123!@#}

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  redis:
#    host: 192.168.70.200
#    port: 6379
#    password: 123456
feign:
  sentinel:
    enabled: true
#security:
#  oauth2:
#    resource:
#      id: rid
#      user-info-uri: http://192.168.70.200:8000/uaa/user-info


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.microservices.admin.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-delete-field: deleted
      id-type: auto

generator:
  filepath: /Users/fadedfat3/Codes/microservices/generator

logging:
  level:
    root: warn
    com.example.microservices.admin: debug